<html>
<!--this page has been edited-->
<head>
<link href="../css/styles.css" rel="stylesheet" type="text/css">
<title>
Leviticus' Website
</title>
</head>

<body>

<h1>
Oil Bath Shaker
</h1>

<address>
<a href="../index.php">leviticusrhoden.com Homepage</a>
</address>
<address>
<a href="pwhresearch.php">Back to PWH Research</a>
</address>

<h2>
What is an Oil Bath Shaker?
</h2>
<p>
As explained in <a href="whatispwh.php">my introduction to Pilot Wave Hydrodynamics</a> (PWH), the model is just a shaking bath of oil. So, we build a machine to shake a dish of oil. In my case it is a speaker on top of some wood posts that I can feed sine waves from my iPhone. This is much in line with other experiments in PWH, at least the lower-cost ones. Of course, one could spend as much as they want to get industry-grade shakers that simulate earthquakes and whatnot, but my simple shaker is more than enough to test some of the phenomena. 
</p><br><br>

<h2>
What is My Oil Bath Shaker?
</h2>
<p>
I built my shaker using mostly parts I had at home. While it is for research at the university, it started as a project I did first for a physics competition, and later for fun. Four pine posts were cut from some scrap I had lying around on my bandsaw, and I cut slots in the lower part of them to hold a plywood shelf. This shelf both holds the posts together and the amplifier circuit that runs the speaker. On the top of posts, I screwed in the speaker. This, while not as professional as I had hoped, does give me some leeway in leveling out the speakers, by tightening the screws fully or leaving them a few millimeters above the posts.
</p>
<img src="photos/my_shaker.jpg" alt="A top front shot of a speaker, with a 3D printed dish on top, bolted onto 4 pine wood posts. Underneath the speaker is mounted a motherboard. Wrapped around the posts is a wire that connects to a wall plug." style="display: block; margin-left: auto; margin-right: auto;">
<br><br>
<p>
    
</p><br><br>
<h2>
Interchangeable 3D Printed Dishes
</h2>
<p>
For the experiments I wanted to run, I needed a way to make different shaped dishes, with a certain topology layout of deep and shallow oil. That lets us make corrals that trap droplets, narrow channels for them to pass through, etc. Starting this mission, I had to design a low force, yet sturdy connection. We have to connect our dishes to a thin metal cylinder that houses the coil in the speaker. I figured I could use the slight bend that thin plastic allows to make a tight fit. 
</p>
<p>
    After some CADing, I got the following models worked up. Since 3D printing is limited in how it makes overhangs, and I didn't want to waste time with supports, so I made the interchangeable dishes two parts. One is the dish itself, with 3 insert holes on the bottom. Then I have the twist collar with 3 posts. This also allowed for easier prototyping, as I could hone the twist part independently of the dishes. On the speaker is also a disk with three slots to mount the dishes on.
</p>
<img src="photos/coral_cad.jpg" alt="A CAD model of a cylinder with a 1/4'' well, and a 1/2'' well in the middle" style="display: block; margin-left: auto; margin-right: auto;">
<figcaption>My dish CAD model, which I can make have any topology depending on the test I want to run. The middle oval is a bit deeper than the rest, so oil droplets stay inside of it.</figcaption>
<br>
<img src="photos/twist_base_cad.jpg" alt="A CAD model of a ring with three posts sticking up on the top face, and 3 thin fingers with triagnles on the tips." style="display: block; margin-left: auto; margin-right: auto;">
<figcaption>My twist base for dishes. The posts insert into the dish shown above. The fingers bend a little when the speaker to twist adapter (shown below) is put in and twisted.</figcaption>
<br>
<img src="photos/speaker_twist_cad.jpg" alt="A CAD model of A center cylindrical post with a flat round head. The head has 3 slots cut out of it, that cut from the outside edge in about halfway along the radius." style="display: block; margin-left: auto; margin-right: auto;">
<figcaption>This piece connects to the speaker coil on the bottom, and is inserted to the twist base & dish assembly above.</figcaption>
<br>
<img src="photos/base_coral_asmb_cad.jpg" alt="A CAD assembly of all the above parts, put together." style="display: block; margin-left: auto; margin-right: auto;">
<figcaption>The assembly of all the above parts.The speaker base and dish are rotated about 1/6th of a rotation from each other to lock the dish on to the speaker.</figcaption>
<br><br>
<p>
    When the base and dish assembly are rotated relative to each other, the triangles on the twist base fingers act like ramps, that allow counterclockwise rotation but not clockwise rotation of the dish. When the dish is turned counterclockwise, a spring force is generated by the deflection of the fingers that holds the dish on tight, while a clockwise rotation will go until the fingers hit the side of the slots in the speaker adapter, making it easy to remove without seeing the underside of the dish.
</p><br><br>

<h2>Conclusion</h2>
<p>
    All in all, I'm impressed with how well this project turned out! This was my first project with my new 3D printer, and I missed how quickly the prototyping process was. In fact, I have a picture that shows well just how many different measurements I tried. 
</p>
<img src="photos/base_progresion.jpg" alt="A CAD assembly of all the above parts, put together." style="display: block; margin-left: auto; margin-right: auto;">
<figcaption>If at first you don't succeed, try, try, try, try again!</figcaption>
<br><p>
    I'm impressed with how well it came together. To deal with some tolerance inconsistancies with 3D printers I place a few pieces of electrical tape on the bottom of the dish. While each print I keep tweaking the numbers a bit to try and get a better fit, this lets me have a well fitting part regardless of how my printer is feeling day to day.
</p>
<address>
<a href="../index.php">leviticusrhoden.com Homepage</a>
</address>
<address>
<a href="pwhresearch.php">Back to PWH Research</a>
</address>
<address><a href = "rss.xml"> RSS Feed</a></address>
<address><a href = "mailto: levi@leviticusrhoden.com">Send Me an E-Mail!</a></address>
</body>

</html>
